Equipo de Inteligencia Competitiva BlackHat:
  agents:
  - Analista de Mercado
  - Investigador Competitivo
  - Estratega
  - Cazador de Oportunidades
  description: "Equipo especializado en an\xE1lisis competitivo, espionaje de mercado\
    \ y descubrimiento de oportunidades ocultas"
  process: hierarchical
  tasks:
  - "An\xE1lisis de Competidores"
  - "An\xE1lisis de Tendencias"
  - "Identificaci\xF3n de Oportunidades"
  - "Plan Estrat\xE9gico"
  verbose: true
